/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#71d7cf",
        "primary-fixed": "#ffdad8",
        "surface-container-high": "var(--color-surface-container-high)",
        "secondary-fixed": "#ffddb8",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "secondary-fixed-dim": "#ffb95f",
        "on-secondary-container": "#5b3800",
        "surface-bright": "var(--color-surface-bright)",
        "inverse-primary": "#bb162c",
        "error": "#ffb4ab",
        "on-tertiary": "#003734",
        "background": "var(--color-background)",
        "on-surface": "var(--color-on-surface)",
        "on-secondary-fixed": "#2a1700",
        "surface-variant": "var(--color-surface-container-highest)",
        "inverse-surface": "#e5e2e1",
        "outline": "var(--color-outline)",
        "tertiary-container": "#32a099",
        "secondary": "var(--color-secondary)",
        "tertiary-fixed": "#8ef4eb",
        "surface-dim": "var(--color-background)",
        "on-tertiary-fixed-variant": "#00504c",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "primary-container": "var(--color-primary-container)",
        "error-container": "#93000a",
        "on-primary-container": "#ffffff",
        "on-secondary": "#472a00",
        "surface-container": "var(--color-surface-container)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "on-primary": "#ffffff",
        "outline-variant": "var(--color-outline-variant)",
        "on-primary-fixed-variant": "#92001c",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-background": "var(--color-on-surface)",
        "on-primary-fixed": "#410007",
        "primary": "var(--color-primary)",
        "surface": "var(--color-surface-container)",
        "secondary-container": "#ee9800",
        "primary-fixed-dim": "#ffb3b1",
        "tertiary-fixed-dim": "#71d7cf",
        "on-error": "#690005",
        "on-tertiary-fixed": "#00201e",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#653e00",
        "surface-tint": "#ffb3b1",
        "inverse-on-surface": "#313030",
        "on-tertiary-container": "#00302d",
        "input-bg": "var(--color-input-bg)",
        "app-border": "var(--color-border)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-sm": "0.75rem",
        "space-xl": "1.5rem",
        "space-2xl": "2rem",
        "space-2xs": "0.25rem",
        "space-lg": "1.25rem",
        "space-xs": "0.5rem",
        "margin-mobile": "1rem",
        "space-md": "1rem",
        "gutter-mobile": "1rem",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "headline-md":   ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md":       ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm":      ["10px", { lineHeight: "12px", letterSpacing: "0.04em", fontWeight: "700" }],
        "headline-lg":   ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-xl-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-lg":      ["14px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-xl":   ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "price-display": ["16px", { lineHeight: "20px", fontWeight: "700" }],
        "body-sm":       ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-lg":       ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "500" }],
        "label-md":      ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
